### PR TITLE
Added scroll up to facing issue button

### PR DESCRIPTION
**Pull request by PranotiPD**
# Issue Title: When we click on facing an issue button it should scroll to top 
*resolve issue:* #76

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## How Has This Been Tested? ⚙️

Tested locally.

### CODE REVIEW

**Review by ashutoshgithubs — APPROVED** [review]
Hi @PranotiPD , This PR is good to merge. Thanks for your valuable code. Please don't limit your contribution here only. Explore the project and keep contributing... Happy Coding :)

**Comment by ashutoshgithubs** [comment]
@PranotiPD you can refer https://github.com/ashutoshgithubs/iemhacks_DEV-G/discussions/81 if you face such problem

**Comment by PranotiPD** [comment]
Hey @ashutoshgithubs I have my email address added there. Still, my name did not get added to the list.

**Comment by ashutoshgithubs** [comment]
@PranotiPD Please don't worry. Working on this part.

**Comment by ashutoshgithubs** [comment]
@PranotiPD  Everything looks fine to me. There maybe be an issue with your github account like sort of missing email or something like restricted account kind of. Kindly check at your end once because all other contributors names are reflected automatically in the contributor section. Let me know.

**Comment by PranotiPD** [comment]
I think it also takes into consideration how many lines of code one has contributed. So let's see after merging other PRs. @ashutoshgithubs

**Pull request merged**
